name: Compile LaTeX Resumes
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Compile LaTeX Resumes
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resumes/*.tex
          working_directory: .
          args: "-pdf -interaction=nonstopmode"

      - name: Move PDFs to pdfs folder
        run: |
          mkdir -p pdfs
          find resumes/ -name "*.pdf" -exec mv {} pdfs/ \;

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes-pdf
          path: pdfs/*.pdf
